spring:
  application:
    name: springcloud-eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
    healthcheck:
          enabled: true
---
server:
  port: 8761
eureka:
  instance:
    hostname: peer1
spring:
  profiles: peer1
---
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
#   register-with-eureka: false
#   fetch-registry: false
spring:
  profiles: peer2